return {
    'drewtempelmeyer/palenight.vim',
    'Numkil/ag.nvim',
    'junegunn/vim-easy-align',
    'sgur/vim-editorconfig',
    'mattn/emmet-vim',
    'tpope/vim-fugitive',
    'junegunn/gv.vim',
    {'fatih/vim-go', ft = {'go'}},
    'junegunn/limelight.vim',
    'junegunn/goyo.vim',
    'reedes/vim-pencil',
    'itchyny/lightline.vim',
    {'iamcco/markdown-preview.nvim', ft = {'markdown'}},
    'mzlogin/vim-markdown-toc',
    'dhruvasagar/vim-table-mode',
    'norcalli/nvim-colorizer.lua',
    'nvim-lua/plenary.nvim',
    'nvim-telescope/telescope.nvim',
    'nvim-treesitter/nvim-treesitter',
    'tpope/vim-commentary',
    'tpope/vim-repeat',
    'tpope/vim-surround',
    'tpope/vim-rails',
    'tpope/vim-vinegar',
    {'tpope/vim-jdaddy', ft = {'json'}},
    'guns/xterm-color-table.vim',
    'prettier/vim-prettier',
    'terrastruct/d2-vim',
    'VonHeikemen/lsp-zero.nvim',
    "williamboman/mason.nvim",
    "williamboman/mason-lspconfig.nvim",
    "neovim/nvim-lspconfig",
    "hrsh7th/nvim-cmp",
    "hrsh7th/cmp-buffer",
    "hrsh7th/cmp-path",
    "saadparwaiz1/cmp_luasnip",
    "hrsh7th/cmp-nvim-lsp",
    "hrsh7th/cmp-nvim-lua",
    "L3MON4D3/LuaSnip",
    "rafamadriz/friendly-snippets",
}
